version: '3'

volumes:
  postgres_data:
    driver: local

services:
  openworld-db:
    image: 'postgres:13.1-alpine'
    container_name: openworld-db
    environment:
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=world
      - POSTGRES_DB=openworld-db
      - POSTGRES_PORT=5444
    ports:
      - "5432:5432"
    volumes:
      - ./openworld-db:/var/lib/postgresql/data

  postgres:
    image: postgres
    container_name: iam-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: iam
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres